import "@/styles/globals.css";

export const metadata = {
  title: "How to Price",
  description: "Generated by Next.js",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="bg-indigo-500">
        <main>{children}</main>
      <footer className="max-w-screen-md mx-auto text-center text-sm">na</footer>
      </body>
    </html>
  );
}
